{
 "title": "ACM - HyperShift Addon",
 "tags": [
  "ACM",
  "Hypershift"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mce_hs_addon_hypershift_operator_degraded_bool,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Individual", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Hosted Control Planes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_available_hosted_clusters_gauge{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Hosted Control Planes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_total_hosted_control_planes_gauge{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HyperShift Operator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HyperShift Addon Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_failed_to_start_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "External DNS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_ext_dns_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HyperShift Operator degraded",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Install in progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_install_in_progress_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Kubeconfig Copy Failures",
   "type": "timeseries",
   "description": "The number of failed Hypershift-addon-operator installs per Hosting Cluster",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "mce_hs_addon_kubeconfig_secret_copy_failure_count{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Placement Score Failures",
   "type": "timeseries",
   "description": "The number of failed attempts to generate a Placement score on a given Hosting Cluster",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mce_hs_addon_placement_score_failure_count{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Install failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_install_failure_gauge{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Fleet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Available Hosted Control Planes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_available_hosted_clusters_gauge)"
    }
   ]
  },
  {
   "title": "Total Hosted Control Planes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_total_hosted_control_planes_gauge)"
    }
   ]
  },
  {
   "title": "HyperShift Operator Degraded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Hypershift Addon Install Failures",
   "type": "graph",
   "description": "The number of failed Hypershift-addon-operator installs per Hosting Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_install_failure_gauge",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "External DNS Degraded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mce_hs_addon_ext_dns_operator_degraded_bool",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Kubeconfig Copy Failures",
   "type": "graph",
   "description": "The number of failed attempts to copy a Hosted Cluster's kubeconfig on a given Hosting Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_kubeconfig_secret_copy_failure_count",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Placement Score Failures",
   "type": "graph",
   "description": "The number of failed attempts to generate a Placement score on a given Hosting Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_placement_score_failure_count",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}