{
 "title": "ACM - HyperShift Addon Cluster",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mce_hs_addon_hypershift_operator_degraded_bool,cluster)"
    }
   },
   { "name": "datastource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "bargauge",
   "description": "HCP: Hosted Control Plane",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(mce_hs_addon_available_hosted_control_planes_gauge{cluster=\"$cluster\"})",
     "legendFormat": "HCP"
    },
    {
     "expr": "sum by (cluster)(mce_hs_addon_available_hosted_clusters_gauge{cluster=\"$cluster\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (cluster)(mce_hs_addon_total_hosted_control_planes_gauge{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SLI - Addon (Range)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\", cluster=\"$cluster\"}[$__range]))/ sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\", cluster=\"$cluster\"}[$__range]))",
     "legendFormat": "Addon Availability"
    }
   ]
  },
  {
   "title": "SLI - Addon (30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\", cluster=\"$cluster\"}[30d]))/ sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\", cluster=\"$cluster\"}[30d]))",
     "legendFormat": "Addon Availability"
    }
   ]
  },
  {
   "title": "Clusters graph",
   "type": "timeseries",
   "description": "HCP: Hosted Control Plane available\n\nAvailable: Cluster with workers available\n\nTotal: Number of clusters",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (cluster)(mce_hs_addon_available_hosted_control_planes_gauge{cluster=\"$cluster\"})",
     "legendFormat": "HCP"
    },
    {
     "expr": "sum by (cluster)(mce_hs_addon_available_hosted_clusters_gauge{cluster=\"$cluster\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (cluster)(mce_hs_addon_total_hosted_control_planes_gauge{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    { "expr": "60", "legendFormat": "Soft max" },
    { "expr": "80", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Install",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_install_failure_gauge{cluster=\"$cluster\"}",
     "legendFormat": "Failures"
    },
    {
     "expr": "mce_hs_addon_install_in_progress_bool{cluster=\"$cluster\"}",
     "legendFormat": "Progressing"
    }
   ]
  },
  {
   "title": "Addon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_failed_to_start_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Placement Score Failures",
   "type": "timeseries",
   "description": "The number of failed attempts to generate a Placement score on a given Hosting Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mce_hs_addon_placement_score_failure_count{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "External DNS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_ext_dns_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HyperShift Operator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Addon Available",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\", cluster=\"$cluster\", condition=\"Available\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HyperShift Operator graph",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Kubeconfig Copy Failures",
   "type": "timeseries",
   "description": "The number of failed Hypershift-addon-operator installs per Hosting Cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "mce_hs_addon_kubeconfig_secret_copy_failure_count{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "MEM"
    }
   ]
  }
 ]
}