{{- if ne .disableMetrics "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .SpokeRolebindingName }}-metrics
  namespace: {{ .AddonInstallNamespace }}
rules:
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["*"]
{{- end }}