apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .AddonName }}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: {{ .AddonName }}
spec:
  podSelector:
    matchLabels:
      app: {{ .AddonName }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
    - port: 8000
      protocol: TCP
