{{- if eq .enableRHOBSMonitoring "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:klusterlet-work:rhobs-role
rules:
  - apiGroups: ["monitoring.rhobs"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}