apiVersion: v1
kind: ServiceAccount
metadata:
  name: mce-discovery-controller
  namespace: multicluster-engine
  labels:
    app: mce-discovery-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mce-discovery-controller
  labels:
    app: mce-discovery-controller
rules:
# ManagedCluster permissions
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters/status
  verbs:
  - get
  - update
  - patch

# ManagedClusterAddOn permissions
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/status
  verbs:
  - get
  - update
  - patch

# AddOnDeploymentConfig permissions
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - addondeploymentconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# ClusterManagementAddOn permissions
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# KlusterletConfig permissions
- apiGroups:
  - config.open-cluster-management.io
  resources:
  - klusterletconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Policy permissions
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies/status
  verbs:
  - get
  - update
  - patch

# Placement permissions
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# PlacementBinding permissions
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - placementbindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# ConfigMap permissions
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# DiscoveredCluster permissions
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters
  verbs:
  - get
  - list
  - watch

# Namespace permissions
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

# Event permissions for controller events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# Leader election permissions
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  resourceNames:
  - mce-discovery-controller-leader-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mce-discovery-controller
  labels:
    app: mce-discovery-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mce-discovery-controller
subjects:
- kind: ServiceAccount
  name: mce-discovery-controller
  namespace: multicluster-engine
