{
 "title": "ACM - HyperShift Addon Fleet",
 "tags": [
  "ACM",
  "Hypershift"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Fleet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clusters",
   "type": "bargauge",
   "description": "HCP: Hosted Control Plane",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_available_hosted_control_planes_gauge)",
     "legendFormat": "HCP"
    },
    {
     "expr": "sum(mce_hs_addon_available_hosted_clusters_gauge)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(mce_hs_addon_total_hosted_control_planes_gauge)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SLI - Addon (30d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d]))/ sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d]))",
     "legendFormat": "Addon Availability"
    }
   ]
  },
  {
   "title": "SLI - Error Budget Consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (21 - (sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d])) - sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d]))))/21",
     "legendFormat": "Addon Availability"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_available_hosted_control_planes_gauge)",
     "legendFormat": "HCP"
    },
    {
     "expr": "sum(mce_hs_addon_available_hosted_clusters_gauge)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(mce_hs_addon_total_hosted_control_planes_gauge)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SLI - Addon Error Budget (min/30d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "21 - (sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d])) - sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d])))",
     "legendFormat": "Remaining Minutes"
    }
   ]
  },
  {
   "title": "SLI - HyperShift Addon Availability (30d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d]))/ sum(count_over_time(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"}[30d]))",
     "legendFormat": "Addon Availability"
    },
    { "expr": "0.99", "legendFormat": "99%" }
   ]
  },
  {
   "title": "Total Hosting Clusters (Management Clusters)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_addon_status_condition{addon_name=\"hypershift-addon\",  condition=\"Available\", status=\"true\"})",
     "legendFormat": "clusters"
    }
   ]
  },
  {
   "title": "Hypershift Addon Install Failures",
   "type": "graph",
   "description": "The number of failed Hypershift-addon-operator installs per Hosting Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_install_failure_gauge",
     "legendFormat": "{{_mc_id}}"
    }
   ]
  },
  {
   "title": "HyperShift Operator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mce_hs_addon_hypershift_operator_degraded_bool",
     "legendFormat": "{{_mc_id}}"
    }
   ]
  },
  {
   "title": "Placement Score Failures",
   "type": "graph",
   "description": "The number of failed attempts to generate a Placement score on a given Hosting Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_placement_score_failure_count",
     "legendFormat": "{{_mc_id}}"
    }
   ]
  },
  {
   "title": "Kubeconfig Copy Failures",
   "type": "graph",
   "description": "The number of failed attempts to copy a Hosted Cluster's kubeconfig on a given Hosting Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mce_hs_addon_kubeconfig_secret_copy_failure_count",
     "legendFormat": "{{_mc_id}}"
    }
   ]
  },
  {
   "title": "External DNS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mce_hs_addon_ext_dns_operator_degraded_bool",
     "legendFormat": "{{_mc_id}}"
    }
   ]
  }
 ]
}