name: Konflux Files Only Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_tekton_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch depth 0 is needed to get full history for accurate diffing
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46 # Use a recent stable version

      - name: Check if only .tekton/ files are changed
        id: tekton-only-check
        run: |
          ONLY_TEKTON_CHANGES="true"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" != ".tekton/"* ]]; then
              echo "Non-.tekton/ file changed: $file"
              ONLY_TEKTON_CHANGES="false"
              break
            fi
          done

          echo "ONLY_TEKTON_CHANGES=$ONLY_TEKTON_CHANGES" >> "$GITHUB_OUTPUT"

      - name: Report status based on changes
        if: ${{ always() }} # Always run this step to set a status
        uses: Sibz/github-status-action@v1.2.0 # Use a stable version for setting status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.tekton-only-check.outputs.ONLY_TEKTON_CHANGES == 'true' && 'success' || 'failure' }}
          description: 'Only .tekton/ files changed (if green)'
          context: 'tekton-only-changes' # This is the name of the status check in GitHub
